config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'
  post 'welcome/contact'
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Primary controller
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# Controller for faces
class WelcomeController < ApplicationController
  invisible_captcha only: [:contact], honeypot: :subtitle

  def index
    @face_show = params[:show] || 'show-front'
  end

  def contact
    respond_to do |format|
      ContactMailer.with(parameters).new_contact_email.deliver_now

      format.html { redirect_to redirected }
    end
  end

  private

  def parameters
    {
      name: params[:name],
      email: params[:email],
      subject: params[:subject],
      message: params[:message]
    }
  end

  def redirected
    {
      controller: :welcome,
      action: :index,
      show: 'show-left',
      na: params[:name],
      em: params[:email],
      su: params[:subject],
      me: params[:message]
    }
  end
end

app/helpers/contact_helper.rb
# frozen_string_literal: true

# Helper for page contact
module ContactHelper
  def field(input, name, text = nil, error = nil)
    capture do
      concat label_tag input, name, class: 'prefix'
      concat text_field_tag input, text, placeholder: error, class: 'form'
    end
  end

  def textarea(input, name, text = nil)
    capture do
      concat label_tag input, name, class: 'prefix'
      concat text_area_tag input, text, class: 'form'
    end
  end
end

app/helpers/link_helper.rb
# frozen_string_literal: true

# Helper for page link
module LinkHelper
  def link_supports(name)
    content_tag :div, class: 'row' do
      concat link_logo(name)
      concat link_text(name)
    end
  end

  private

  def link_logo(name)
    content_tag :div, class: 'image-logo' do
      image_tag "#{name}.png", width: 100
    end
  end

  def link_text(name)
    content_tag :p, class: 'desc' do
      link_to t("welcome.faces.link.#{name}.link") do
        content_tag(:strong, t("welcome.faces.link.#{name}.title"))
      end
    end
  end
end

app/helpers/my_helper.rb
# frozen_string_literal: true

# Helper for page my
module MyHelper
  def cv_link
    "cv-#{define_locale}.pdf"
  end
end

app/helpers/social_helper.rb
# frozen_string_literal: true

# Helper for page social
module SocialHelper
  def social(name, link)
    content_tag :div, class: 'row' do
      content_tag :div, class: 'describ' do
        concat social_logo(name)
        concat social_describ(name, link)
      end
    end
  end

  private

  def social_logo(name)
    content_tag :div, class: 'image-logo' do
      image_tag "#{name}.svg", width: 100
    end
  end

  def social_describ(name, link)
    content_tag :div, class: 'title' do
      concat social_describ_title(name, link)
      concat social_describ_text(name)
    end
  end

  def social_describ_title(name, link)
    content_tag :div do
      link_to link do
        content_tag :h3, t("welcome.faces.social.#{name}.title")
      end
    end
  end

  def social_describ_text(name)
    content_tag :div do
      t("welcome.faces.social.#{name}.describ")
    end
  end
end

app/helpers/technology_helper.rb
# frozen_string_literal: true

# Helper for page technology
module TechnologyHelper
  def techno(image, _text)
    content_tag :div, class: 'techno' do
      techno_image(image)
    end
  end

  private

  def techno_image(image)
    content_tag :div, class: 'image' do
      image_tag image
    end
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

# Helper for each component to face
module WelcomeHelper
  def fa_icon(image)
    image_tag image, size: '25x25'
  end

  def buttons_cube(direction, classe, container)
    content_tag :div, class: "buttons #{container}-button" do
      content_tag :div, class: "show-#{direction}" do
        classe.html_safe
      end
    end
  end

  def define_locale
    params.key?(:locale) ? params[:locale] : I18n.default_locale
  end

  def selector_languages_data
    [
      ['Français', :fr],
      ['English', :en]
    ]
  end
end

app/helpers/work_helper.rb
# frozen_string_literal: true

# Helper for page work
module WorkHelper
  def project_view(name, playstore)
    content_tag :div, class: "row #{name}" do
      concat project_view_title(name, playstore)
      concat project_view_describ(name)
    end
  end

  private

  def project_view_title(name, playstore)
    content_tag :div, class: 'title' do
      content_tag :div do
        concat project_view_title_image(name)
        concat project_view_title_name(name, playstore)
      end
    end
  end

  def project_view_title_name(name, playstore)
    content_tag :div, class: 'title' do
      concat project_view_title_text(name)
      concat project_view_title_link(playstore)
    end
  end

  def project_view_title_image(name)
    content_tag :div, class: 'image-logo' do
      image_tag "#{name}.png", width: 100
    end
  end

  def project_view_title_text(name)
    content_tag :h3 do
      link_to t("welcome.faces.work.#{name}.link") do
        t "welcome.faces.work.#{name}.title"
      end
    end
  end

  def project_view_title_link(playstore)
    content_tag :h3 do
      link_to playstore, class: 'play-store' do
        image_tag 'play-store-download.png', height: 64
      end
    end
  end

  def project_view_describ(name)
    content_tag :p, class: 'describ' do
      t "welcome.faces.work.#{name}.describ"
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html{ lang: define_locale }
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    = favicon_link_tag 'favicon.png', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'screen'
    = csrf_meta_tags
    %title
      = Settings.meta_site
  %body
    %section
      = yield
    = javascript_include_tag 'application'

app/views/layouts/contact.html.haml
!!!
%html{ lang: 'fr' }
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    = favicon_link_tag 'favicon.png', type: 'image/png'
  %body
    %h1
      = t 'layout.contact.title'
    %p
      = t 'layout.contact.subject'
      = @subject
    %p
      = t 'layout.contact.name'
      = @name
    %p
      = t 'layout.contact.mail'
      = @email
    %p
      = @message

app/views/welcome/_faces.html.haml
- active = "#{face[5].code} #{face[0].content}"
- if face[5].code == 'front'
  - active << ' active'

%figure{ class: active }
  .containers-cube
    %div.languages
      = image_tag 'language.svg'
      = form_with url: welcome_index_path, method: :get do |form|
        = form.select :locale, options_for_select(selector_languages_data, define_locale)
        = form.submit t 'layout.language.send'
    %h2.title
      = t "welcome.faces.#{face[0].content}.title"
    = render "welcome/faces/#{face[0].content}"
    .show-buttons
      = buttons_cube(face[1].up, '&uarr;', 'top')
      = buttons_cube(face[3].right, '&rarr;', 'right')
      = buttons_cube(face[4].down, '&darr;', 'bottom')
      = buttons_cube(face[2].left, '&larr;', 'left')

app/views/welcome/faces/_link.html.haml
.icon-face
  = fa_icon 'link'
.container-faces
  = link_supports 'stilobique'
  = link_supports 'framasoft'
  = link_supports 'liberapay'
  = link_supports 'quadrature'

app/views/welcome/faces/_mail.html.haml
.icon-face= fa_icon 'mail'
.container-faces
  = form_tag welcome_contact_path, id: 'form-contact' do
    = invisible_captcha :subtitle, :topic
    .row
      = field(:name, t('welcome.faces.mail.name.title'), params[:na],
        params[:error] || t('welcome.faces.mail.name.placeholder'))
    .row
      = field(:email, t('welcome.faces.mail.email.title'), params[:em],
        params[:error] || t('welcome.faces.mail.email.placeholder'))
    .row
      = field(:subject, t('welcome.faces.mail.subject.title'), params[:su],
        params[:error] || t('welcome.faces.mail.subject.placeholder'))
    .row.textarea
      = textarea(:message, t('welcome.faces.mail.text.title'), params[:me])
    .row.last
      = submit_tag t('welcome.faces.mail.send')

%ul.vcard
  %li
    %strong VAILLANT Jeremy
  %li
    49 rue de lorient
  %li
    35000 Rennes
  %li
    = mail_to 'vaillant.jeremy@dev-crea.com', 'vaillant.jeremy[@]dev-crea.com'

app/views/welcome/faces/_my.html.haml
.icon-face= fa_icon 'user'
%p.container-faces
  = image_tag 'logo.png', class: 'dev-crea', alt: 'Logo Dev Crea'
  %strong
    = t('welcome.faces.my.describ')
  %br
  %br
  %br
  = t('welcome.faces.my.post')
  %br
  %br
  = t('welcome.faces.my.vision')
  %br
  %br
  = t('welcome.faces.my.conclusion')
  %br
  %br
  = link_to asset_url cv_link do
    = fa_icon 'pdf'
    = t('welcome.faces.my.download')

app/views/welcome/faces/_social.html.haml
.icon-face= fa_icon 'social'
.container-faces
  = social 'gitlab',
    'https://framagit.org/GRem'
  = social 'github',
    'https://github.com/Dev-Crea'
  = social 'mastodon',
    'https://mamot.fr/web/accounts/40730'

app/views/welcome/faces/_tech.html.haml
.icon-face= fa_icon 'tech'
.container-faces
  = techno 'aws.svg', 'AWS'
  = techno 'docker.svg', 'Docker'
  = techno 'godot.svg', 'Godot'
  = techno 'git.svg', 'Git'
  = techno 'grafana.svg', 'Grafana'
  = techno 'kotlin.svg', 'Kotlin'
  = techno 'mongodb.svg', 'MongoDB'
  = techno 'packer.svg', 'Packer'
  = techno 'python.svg', 'Python'
  = techno 'rails.svg', 'Rails'
  = techno 'ruby.svg', 'Ruby'
  = techno 'terraform.svg', 'Terraform'
  = techno 'vuejs.svg', 'VueJS'

app/views/welcome/faces/_work.html.haml
.icon-face= fa_icon('work')
.container-faces
  = project_view 'openbd',
    'https://play.google.com/store/apps/details?id=gui.android.openbd'
  = project_view 'puzzlequest',
    'https://play.google.com/store/apps/details?id=org.godotengine.puzzlequest'

app/views/welcome/index.html.haml
#body
  .container
    #cube{ class: "cube-show #{@face_show}" }
      - [Settings.faces.front, Settings.faces.back, Settings.faces.right,
        Settings.faces.left, Settings.faces.top,
        Settings.faces.bottom].each do |value|
        = render partial: 'faces', locals: { face: value }

#keys
  .row
    %h3 Aide à la navigation :
    %p Utilisez le clavier pour naviguer sur le cube.
  .row.keyboard
    .touch
      %span
    .touch
      %span.key Z / W
    .touch
      %span
  .row.keyboard
    .touch
      %span.key S
    .touch
      %span.key Q / A
    .touch
      %span.key D